/**
 * Board layouts.
 *
 * Coordinates are in *tile units*: a tile occupies exactly 1.0 x 1.0 and sits
 * at integer or half-integer offsets. Half offsets are what give the classic
 * arrangements their staggered look, so `x` and `y` are floats, not ints.
 *
 * Each layout is written as ASCII art, one grid per layer, because that is the
 * only form of this data a human can actually edit. `#` marks a tile origin;
 * anything else is empty. `extras` covers the handful of tiles that sit off the
 * grid (the turtle's flippers, its crown).
 *
 * These are geometric arrangements, generated by the code below from our own
 * ASCII source. No layout file, sprite sheet, or coordinate table from any
 * commercial mahjong title was used.
 */

export interface Cell {
  readonly x: number;
  readonly y: number;
  readonly z: number;
}

interface LayerSpec {
  /** Grid origin in tile units. May be fractional. */
  readonly offset: readonly [number, number];
  readonly rows: readonly string[];
}

interface LayoutSpec {
  readonly id: LayoutId;
  readonly name: string;
  /** Shown nowhere in the UI by default — difficulty is silent. Docs only. */
  readonly relativeDifficulty: number;
  readonly layers: readonly LayerSpec[];
  readonly extras?: readonly Cell[];
}

export type LayoutId = 'turtle' | 'pyramid' | 'dragon';

export interface Layout {
  readonly id: LayoutId;
  readonly name: string;
  readonly relativeDifficulty: number;
  readonly cells: readonly Cell[];
  /** Bounding box in tile units, including the 1.0 width of the far tiles. */
  readonly bounds: { minX: number; minY: number; maxX: number; maxY: number };
  readonly maxZ: number;
}

const SPECS: readonly LayoutSpec[] = [
  {
    // The classic turtle: 87 on the ground, a 6x6 shell, then 4x4, 2x2, and a
    // single tile on the crown. 144 tiles.
    id: 'turtle',
    name: 'Turtle',
    relativeDifficulty: 0.55,
    layers: [
      {
        offset: [0, 0],
        rows: [
          '.############..',
          '...########....',
          '..##########...',
          '.############..',
          '.############..',
          '..##########...',
          '...########....',
          '.############..',
        ],
      },
      { offset: [3, 1], rows: ['######', '######', '######', '######', '######', '######'] },
      { offset: [4, 2], rows: ['####', '####', '####', '####'] },
      { offset: [5, 3], rows: ['##', '##'] },
    ],
    extras: [
      // Flippers, and the tile balanced on the crown.
      { x: 0, y: 3.5, z: 0 },
      { x: 13, y: 3.5, z: 0 },
      { x: 14, y: 3.5, z: 0 },
      { x: 5.5, y: 3.5, z: 4 },
    ],
  },
  {
    // Garden Steps. An original, softly tapered arrangement for the first
    // board: broad readable edges, staggered shoulders, and a narrow raised
    // spine. It retains 144 tiles and the same 10 x 8 footprint as the former
    // rectangular pyramid, so phone tiles stay large without presenting a
    // visible uniform grid.
    id: 'pyramid',
    name: 'Garden Steps',
    relativeDifficulty: 0.3,
    layers: [
      {
        offset: [0, 0],
        rows: [
          '..######..',
          '.########.',
          '##########',
          '##########',
          '##########',
          '##########',
          '.########.',
          '..######..',
        ],
      },
      {
        offset: [0, 1],
        rows: [
          '.########.',
          '##########',
          '##########',
          '##########',
          '##########',
          '.########.',
        ],
      },
      {
        offset: [2, 2],
        rows: ['.####.', '######', '######', '.####.'],
      },
    ],
  },
  {
    // A broad winged body with a deep spine. Hardest of the three: the centre
    // column is four layers deep and the wings block from both sides.
    id: 'dragon',
    name: 'Dragon',
    relativeDifficulty: 0.85,
    layers: [
      {
        offset: [0, 0],
        rows: [
          '....##########....',
          '..##############..',
          '##################',
          '##################',
          '..##############..',
          '....##########....',
        ],
      },
      { offset: [4, 1], rows: ['##########', '##########', '##########', '##########'] },
      { offset: [6, 2], rows: ['########', '########'] },
      { offset: [8, 2], rows: ['##', '##'] },
    ],
  },
];

function buildLayout(spec: LayoutSpec): Layout {
  const cells: Cell[] = [];

  spec.layers.forEach((layer, z) => {
    const [ox, oy] = layer.offset;
    layer.rows.forEach((row, ry) => {
      for (let rx = 0; rx < row.length; rx++) {
        if (row[rx] === '#') cells.push({ x: ox + rx, y: oy + ry, z });
      }
    });
  });

  for (const extra of spec.extras ?? []) cells.push(extra);

  if (cells.length % 2 !== 0) {
    throw new Error(`Layout "${spec.id}" has an odd cell count (${cells.length})`);
  }

  const bounds = cells.reduce(
    (acc, c) => ({
      minX: Math.min(acc.minX, c.x),
      minY: Math.min(acc.minY, c.y),
      maxX: Math.max(acc.maxX, c.x + 1),
      maxY: Math.max(acc.maxY, c.y + 1),
    }),
    { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity },
  );

  return {
    id: spec.id,
    name: spec.name,
    relativeDifficulty: spec.relativeDifficulty,
    cells,
    bounds,
    maxZ: cells.reduce((m, c) => Math.max(m, c.z), 0),
  };
}

export const LAYOUTS: Readonly<Record<LayoutId, Layout>> = Object.freeze(
  Object.fromEntries(SPECS.map((s) => [s.id, buildLayout(s)])) as Record<LayoutId, Layout>,
);

export const LAYOUT_IDS = SPECS.map((s) => s.id);

/** Layouts ordered easiest to hardest. Consumed by the difficulty model. */
export const LAYOUTS_BY_DIFFICULTY: readonly Layout[] = Object.values(LAYOUTS).sort(
  (a, b) => a.relativeDifficulty - b.relativeDifficulty,
);
